// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9RKCH66rynUzO6_ILNuCUElSN06AfnIY',
    appId: '1:1004559255461:web:236086a7ddb5b243e80a4c',
    messagingSenderId: '1004559255461',
    projectId: 'tshikota-eats',
    authDomain: 'tshikota-eats.firebaseapp.com',
    databaseURL: 'https://tshikota-eats-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tshikota-eats.firebasestorage.app',
    measurementId: 'G-0521W3593G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwATLcneKIQTtIA0rB09am2tncHpp_lsc',
    appId: '1:1004559255461:android:c94cc62000812e3ee80a4c',
    messagingSenderId: '1004559255461',
    projectId: 'tshikota-eats',
    databaseURL: 'https://tshikota-eats-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tshikota-eats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBvtoXBdbmjHtty1cWTIsoXBTkm98Gj4',
    appId: '1:1004559255461:ios:d231f4b64a916eabe80a4c',
    messagingSenderId: '1004559255461',
    projectId: 'tshikota-eats',
    databaseURL: 'https://tshikota-eats-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tshikota-eats.firebasestorage.app',
    iosClientId: '1004559255461-52964nejcfjilvu2sb2s9gsvmsjosfck.apps.googleusercontent.com',
    iosBundleId: 'com.example.tshikotaEatsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhBvtoXBdbmjHtty1cWTIsoXBTkm98Gj4',
    appId: '1:1004559255461:ios:d231f4b64a916eabe80a4c',
    messagingSenderId: '1004559255461',
    projectId: 'tshikota-eats',
    databaseURL: 'https://tshikota-eats-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tshikota-eats.firebasestorage.app',
    iosClientId: '1004559255461-52964nejcfjilvu2sb2s9gsvmsjosfck.apps.googleusercontent.com',
    iosBundleId: 'com.example.tshikotaEatsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9RKCH66rynUzO6_ILNuCUElSN06AfnIY',
    appId: '1:1004559255461:web:735fda034b433c4ae80a4c',
    messagingSenderId: '1004559255461',
    projectId: 'tshikota-eats',
    authDomain: 'tshikota-eats.firebaseapp.com',
    databaseURL: 'https://tshikota-eats-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tshikota-eats.firebasestorage.app',
    measurementId: 'G-E7S8P76C8T',
  );
}
